config/routes.rb
Rails.application.routes.draw do

	resources :topics, only: [:index, :show]

	devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register'}
	  
	resources :portfolios, except: [:show]
	
	resources :portfolios do
	  member do
		patch :move
	  end
	end
	
	resources :blogs do
		member do
			get :toggle_status
		end
	end

	mount ActionCable.server => '/cable'


	root to: 'pages#home'

	get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'
	get 'about', to: 'pages#about'
	get 'contact', to: 'pages#contact'
	get 'tech-news', to: 'pages#tech_news'
	get 'angular-items', to: 'portfolios#angular'

end

app/models/portfolio.rb
class Portfolio < ApplicationRecord

	acts_as_list

	has_many :technologies, :dependent => :destroy

	accepts_nested_attributes_for 	:technologies, 
									reject_if: lambda { |attrs| attrs['name'].blank? }

	validates_presence_of :title, :body

	mount_uploader :thumb_image, PortfolioUploader
	mount_uploader :main_image, PortfolioUploader

	def self.angular
		where(subtitle: "Angular")
	end


	scope :ruby_on_rails, -> {where(subtitle: "Ruby on Rails")}
	
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
	before_action :set_portfolio_item, only: [:edit, :show, :update, :destroy, :move]
	layout 'portfolio'
	access  all: [:show, :index, :angular], 
          	user: {except: [:destroy, :new, :create, :update, :edit]}, 
          	site_admin: :all

	def index
		@portfolio_items = Portfolio.all
		# @portfolio_items = Portfolio.where(subtitle: "Angular")
		# @portfolio_items = Portfolio.angular
		# @portfolio_items = Portfolio.ruby_on_rails
	end

	def angular
		@angular_portfolio_items = Portfolio.angular
	end

	def new
		@portfolio_item = Portfolio.new
		# @portfolio_item.technologies.build
	end

	def create
    	@portfolio_item = Portfolio.new(portfolio_params)

	    respond_to do |format|
	      	if @portfolio_item.save
	        	format.html { redirect_to portfolios_path, notice: 'Portfolio was successfully created.' }
	      	else
	        	format.html { render :new }
	      	end
		end
	end

	def edit
	end

	def update
	    respond_to do |format|
	      if @portfolio_item.update(portfolio_params)
	        format.html { redirect_to portfolios_path, notice: 'The record was successfully updated.' }
	      else
	        format.html { render :edit }
	      end
	    end
  	end

  	def show
  	end

  	 def destroy
  	 	# Destroy the record
	    @portfolio_item.destroy

	    # Redirect
	    respond_to do |format|
	      format.html { redirect_to portfolios_url, notice: 'Record Removed!' }
    end
  end

  def move
	@portfolio_item.insert_at(params[:position].to_i)
	head :ok
  end

  private

  	def portfolio_params
  		params.require(:portfolio).permit(	:title, 
  										  	:subtitle, 
											:body,
											:thumb_image,
											:main_image,
  										  	technologies_attributes: [:id, :name, :_destroy]
  										  )
  	end

  	def set_portfolio_item
  		@portfolio_item = Portfolio.find(params[:id])
  	end

end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
    def image_generator(height:, width:)
        "http://placehold.it/#{height}x#{width}"
    end

    def portfolio_img img, type
        if img
            img
        elsif type == 'thumb'
            image_generator(height: '350', width: '200')
        elsif type == 'main'
            image_generator(height: '600', width: '400')
        end
    end

end
 

app/views/portfolios/_form.html.erb
<%= form_with(model: @portfolio_item, local: true) do |form| %>
    
    <% if @portfolio_item.errors.any? %>
    <%# This doesn't work right now - add_gritter issue %>
        <%= @portfolio_item.errors.full_messages.each do |error| %>
            <%= alertgen error, "custom_gritter_portfolio" %>
        <% end %>
    <% end %>

<div class="form-row">
    <div class="form-group col-md-6">
        <div class="form-group">
            <%= form.label :title %>
            <%= form.text_field :title, class: 'form-control' %>
        </div>
    </div>
    <div class="form-group col-md-6">
        <div class="form-group">
            <%= form.label :subtitle %>
            <%= form.text_field :subtitle, class: 'form-control' %>
        </div>
    </div>
</div>

<div class="form-row">
    <div class="form-group col-md-6">
        <div class="form-group">
            <label class="btn btn-primary btn-block">
                Upload a main image <%= form.file_field :main_image, style: 'display:none;' %>
            </label>

        </div>
    </div>
    <div class="form-group col-md-6">
        <div class="form-group">
            <label class="btn btn-primary btn-block">
                Upload a thumb image <%= form.file_field :thumb_image, style: 'display:none;' %>
            </label>
        </div>
    </div>
</div>


<div class="form-group">
    <%= form.label :body %>
    <%= form.text_area :body, class: 'form-control', rows: 15 %>
</div>

<hr>

<h2>Technologies Used: </h2>

<div class="form-group">
    <%= form.fields_for :technologies do |tech_form| %>

    <%= render 'technology_fields', form: tech_form %>
    <% end %>

    <div class="form-row links">
        <%= link_to_add_association 'Add Technology', form, :technologies, form_name: 'form' %>
    </div>


</div>

<div class="form-group">
    <%= form.submit 'Save Portfolio Item', class: 'btn btn-primary btn-block' %>
</div>

<% end %>

app/views/portfolios/_portfolio_item.html.erb
<div data-id="<%= portfolio_item.id %>" class="col-md-4 mb-2">
    <div class="card mb-4 shadow-sm h-100">
        <%= image_tag portfolio_img(portfolio_item.thumb_image.thumb_v.url, 'thumb') %>
        <div class="card-body">
            <span>

            </span>
            <%= portfolio_item.subtitle %>
            <p class="card-text">

                <span>
                    <%= portfolio_item.body.truncate_words(15, seperator: ' ') %>

                </span>
        </div>
        <div class="d-flex justify-content-between align-items-center p-2">
            <div class="btn-group">
                <%= link_to portfolio_item.title.titleize.tr(':', ''), portfolio_show_path(portfolio_item), class: "btn btn-sm btn-outline-primary" %>
                <%= link_to 'Edit', edit_portfolio_path(portfolio_item), class: "btn btn-sm btn-outline-secondary" if logged_in?(:site_admin) %>
            </div>
            <% if logged_in?(:site_admin) %>
            <%= fa_icon "th-large" %>
            <% end %>
            <span class="text-muted"><%= distance_of_time_in_words(portfolio_item.created_at, Time.now) %> ago</span>
        </div>
    </div>
</div>

app/views/portfolios/_technology_fields.html.erb
<div class="form-group nested-fields">
    <div class="field">
        <%= form.label :name %>
        <br>
        <%= form.text_field :name, class: 'form-control' %>
        <div class="float-right">
            <%= link_to_remove_association 'Remove Technology', form, form_name: 'form' %>
        </div>

    </div>
</div>

app/views/portfolios/angular.html.erb
<h1>Angular Portfolio Items</h1>

<!-- <a href="portfolios/new">Create New Item</a> -->

<%=	link_to "Create New Item", new_portfolio_path if logged_in?(:site_admin) %>

<!-- <p>
	<%= new_portfolio_path %>
	<%= new_portfolio_url %>
</p> -->

<% @angular_portfolio_items.each do |portfolio_item| %>
	<p><%= link_to portfolio_item.title, portfolio_show_path(portfolio_item) %></p>
	<p><%= portfolio_item.subtitle %></p>
	<p><%= portfolio_item.body %></p>
	<%= image_tag portfolio_item.thumb_image unless portfolio_item.thumb_image.nil? %>
	<%= link_to "Edit Item", edit_portfolio_path(portfolio_item) if logged_in?(:site_admin) %>
	<%= link_to 'Delete Item', portfolio_path(portfolio_item), method: :delete, data: { confirm: 'Are you sure?' } if logged_in?(:site_admin) %>
	<!-- <a href="/portfolios/<%= portfolio_item.id %>/edit">Edit</a> -->
<% end %>

app/views/portfolios/edit.html.erb
<div class="container portfolio-form">

    <h1>Edit this Portfolio Item</h1>

    <%= render 'form', portfolio_item: @portfolio_item %>

</div>

app/views/portfolios/index.html.erb
<div class="album py-5 bg-light">
    <div class="container">
        <%= source_helper("alert alert-info") %>

        <div class="row" id="<%= "draggable" if logged_in?(:site_admin) %>" data-controller="<%= "drag" if logged_in?(:site_admin) %>" data-drag-url="/portfolios/:id/move">
            <%= render partial: 'portfolio_item', collection: @portfolio_items %>
            <% @portfolio_items.order(position: :asc) %>
        </div>
    </div>
</div>

app/views/portfolios/new.html.erb
<div class="container portfolio-form">
    <h1>Create a new Portfolio</h1>

    <%= render 'form', portfolio_item: @portfolio_item %>

</div>

app/views/portfolios/show.html.erb
<div class="container portfolio-form">
    <div class="d-flex flex-row">
        <div class="p-2 flex-fill">
            <%= image_tag portfolio_img(@portfolio_item.main_image.main_v.url, 'main') %>
        </div>
        <div class="pl-4 flex-fill">
            <h1><%= @portfolio_item.title %></h1>
            <hr>
            <em><%= @portfolio_item.subtitle %></em>
            <p><%= @portfolio_item.body%></p>
            <hr>

            <% if @portfolio_item.technologies.exists? %>

                <h3>Technologies</h3>
                <% @portfolio_item.technologies.each do |t| %>
                <p> <%= t.name %> </p>
                <% end %>
            <% end %>

            <% if logged_in?(:site_admin) %>
            <div class="text-center">
                <%= link_to "Edit Portfolio", edit_portfolio_path(@portfolio_item), class: 'btn btn-warning' %>
            </div>
            <% end %>
        </div>
    </div>
</div>