config/routes.rb
Rails.application.routes.draw do

	resources :topics, only: [:index, :show]

	devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register'}
	  
	resources :portfolios, except: [:show]
	
	resources :portfolios do
	  member do
		patch :move
	  end
	end
	
	resources :blogs do
		member do
			get :toggle_status
		end
	end

	mount ActionCable.server => '/cable'


	root to: 'pages#home'

	get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'
	get 'about', to: 'pages#about'
	get 'contact', to: 'pages#contact'
	get 'tech-news', to: 'pages#tech_news'
	get 'angular-items', to: 'portfolios#angular'

end

app/views/shared/_application_footer.html.erb
<footer class="mastfoot mt-auto">
	<div class="inner">
		<p id="app-footer"><%= copyright_generator %></p>
	</div>
</footer>

app/views/shared/_application_nav.html.erb
<header class="masthead mb-auto">
	<div class="inner"> 
		<h3 class="masthead-brand">Jake Duchesne</h3>
		<nav class="nav nav-masthead justify-content-center app-nav">
			<%= nav_helper 'nav-link', 'span' %>
			<%= login_helper "nav-link" %>
		</nav>
	</div>
</header>

app/views/shared/_blog_footer.html.erb
<footer class = "blog-footer">
  	<%= copyright_generator %>
</footer>

app/views/shared/_blog_masthead.html.erb
<header class="blog-header py-3">
  <div class="row flex-nowrap justify-content-between align-items-center">
    <div class="col-12 text-center">
      <h1 class="blog-header-logo text-dark">Blog Homepage</h1>
    </div>
  </div>
</header>

app/views/shared/_blog_nav.html.erb
<div class="nav-scroller py-1 mb-2">
    <nav class="nav d-flex justify-content-between">
        <%= nav_helper 'nav-link p-2 text-muted style-link', 'span' %>
        <%= login_helper "nav-link p-2 text-muted style-link" %>
    </nav>
</div>

app/views/shared/_blog_sidebar.html.erb
<aside class="col-md-4 blog-sidebar">

    <%= source_helper("alert alert-info") %>

    <div class="p-4 mb-3 bg-light rounded">
        <h4 class="font-italic">About</h4>
        <p class="mb-0">Posts from the nether realm</p>
    </div>

    <div class="p-4 mb-3 social-box bg-light rounded">
        <h4 class="font-italic">Find Me Elsewhere!</h4>
        <ol class="list-unstyled social-links">
            <li><a href="https://github.com/jake-duchesne"><%= fa_icon "github" %></a></li>
            <li class="social-links"><a href="https://linkedin.com/in/jake-duchesne"><%= fa_icon "linkedin" %></a></li>
            <li><a href="https://www.instagram.com/ohc_nada/"><%= fa_icon "instagram" %></a></li>
            <li><a href="https://twitter.com/ohc_nada"><%= fa_icon "twitter" %></a></li>

        </ol>
    </div>

    <div class="p-4 mb-3 bg-light rounded">

        <h4><%= link_to "Topics", topics_path, class: '' %></h4>
        <hr>

        <% @side_bar_topics.each do |topic| %>
        <p><%= link_to topic.title, topic_path(topic) %></p>
        <% end %>


    </div>
</aside>

app/views/shared/_nav.html.erb
<div class="<%= location %>">
  <div> <%= link_to "Home", root_path %> </div>
  <div> <%= link_to "About", about_path %> </div>
  <div> <%= link_to "Contact", contact_path %> </div>
  <div> <%= link_to "Blogs", blogs_path %> </div>
  <div> <%= link_to "Portfolios", portfolios_path %> </div>
</div>

app/views/shared/_portfolio_footer.html.erb
<footer class="portfolio-footer">
    <div class="container">
        <p class="float-right">
            <% if !current_page?(portfolios_path) %>
            <%= link_to "Return to Portfolios", portfolios_path %> |
            <% end %>
            <a href="#">Beam me up!</a>
        </p>
        <%= copyright_generator %>
    </div>
</footer>

app/views/shared/_portfolio_masthead.html.erb
<section class="jumbotron text-center">
  <div class="container">
    <h1>My Portfolio</h1>
    <p class="lead text-muted">I'm always looking to create, learn and understand. Below is a collection of some of the work that I've done to build my skillset as a developer. If you want to know more about me or see what I'm up to now, click one of the links below to find out more!</p>
    <p>
      <%= link_to "About Me", about_path, class: "btn btn-primary" %>
      <%= link_to "My Blog", blogs_path, class: "btn btn-secondary" %>
    </p>
  </div>
</section>

app/views/shared/_portfolio_nav.html.erb
<header>
    <div class="collapse bg-dark" id="navbarHeader">
        <div class="container">
            <div class="row">
                <div class="col-sm-8 col-md-7 py-4">
                    <h4 class="text-white">About</h4>
                    <p class="text-muted">This is a collection of projects, work and examples that I have worked on in the past.</p>
                </div>
                <div class="col-sm-4 offset-md-1 py-4">
                    <h4 class="text-white">Explore</h4>
                    <ul class="list-unstyled">
                        <%= nav_helper 'text-white', 'li' %>
                        <li><%= login_helper "text-white" %></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="navbar navbar-dark bg-dark shadow-sm">
        <div class="container d-flex justify-content-between">
            <a href="#" class="navbar-brand d-flex align-items-center">
                <strong><span><%= fa_icon "user" %></span> Jake Duchesne</strong>
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
        </div>
    </div>
</header>